name: Docker update description

on:
  push:
    branches: 
      - main
    paths:
      - README.md
      - .github/workflows/docker_update_desc.yml

env:
  # Image name at docker hub
  IMAGE_NAME: zinen2/alpine-pigpiod

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        
      - name: Modify readme on Docker Hub
        run: |
          # Add link to this github repo as the titel on Docker Hub
          sed -i 's/# docker-alpine-pigpiod/# [alpine-pigpiod on github](https:\/\/github.com\/zinen\/docker-alpine-pigpiod)/' README.md
        
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ env.IMAGE_NAME }}
